name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cargo:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: rust
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Nix fmt check
        run: nix fmt --check

      - name: Cargo check
        run: nix develop --command cargo check --all

      - name: Cargo clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo fmt check
        run: nix develop --command cargo fmt --all -- --check

      - name: Cargo test
        run: nix develop --command cargo test --all

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: rust
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Nix flake check
        run: nix flake check

      - name: Nix build
        run: nix build
